import type { SkillRecord } from "./types.js";

export const TRUSTED_SKILLS: SkillRecord[] = [
  {
    id: "maxx-onboarding",
    version: "0.1.0",
    purpose: "Capture a plain-language mission handoff.",
    source: "pi-packages/maxx/skills/maxx-onboarding/SKILL.md",
    health: "ready",
    mutation: "mutating",
    approvalPolicy: "approval_required",
    requiredEnvironment: [],
    filesystemPermissions: ["ops/reports"],
    browserPermissions: [],
  },
  {
    id: "maxx-gsap-motion",
    version: "0.1.0",
    purpose: "Tune MAXX motion and visual sequencing.",
    source: "pi-packages/maxx/skills/maxx-gsap-motion/SKILL.md",
    health: "ready",
    mutation: "mutating",
    approvalPolicy: "approval_required",
    requiredEnvironment: [],
    filesystemPermissions: ["src"],
    browserPermissions: ["screenshot"],
  },
  {
    id: "maxx-browser-verify",
    version: "0.1.0",
    purpose: "Run remote browser smoke checks.",
    source: "pi-packages/maxx/skills/maxx-browser-verify/SKILL.md",
    health: "degraded",
    mutation: "read_only",
    approvalPolicy: "automatic",
    requiredEnvironment: ["MAXX_BROWSER_WS_ENDPOINT"],
    filesystemPermissions: [],
    browserPermissions: ["navigate", "extract", "screenshot"],
    command: ["npm", "run", "maxx:browser-smoke", "--"],
  },
  {
    id: "maxx-code-search",
    version: "0.1.0",
    purpose: "Find exact symbols and configuration with minimal context.",
    source: "pi-packages/maxx/skills/maxx-code-search/SKILL.md",
    health: "ready",
    mutation: "read_only",
    approvalPolicy: "automatic",
    requiredEnvironment: [],
    filesystemPermissions: ["repository:read"],
    browserPermissions: [],
  },
  {
    id: "maxx-video-dossier",
    version: "0.1.0",
    purpose: "Create a source-backed video pattern dossier.",
    source: "pi-packages/maxx/skills/maxx-video-dossier/SKILL.md",
    health: "degraded",
    mutation: "mutating",
    approvalPolicy: "approval_required",
    requiredEnvironment: ["FIRECRAWL_API_KEY"],
    filesystemPermissions: ["ops/reports"],
    browserPermissions: ["navigate", "extract"],
    command: ["npm", "run", "maxx:video-dossier", "--"],
  },
  {
    id: "maxx-opusclip",
    version: "0.1.0",
    purpose: "Create clips and gated media actions from owned video.",
    source: "pi-packages/maxx/skills/maxx-opusclip/SKILL.md",
    health: "degraded",
    mutation: "mutating",
    approvalPolicy: "approval_required",
    requiredEnvironment: ["OPUSCLIP_API_KEY"],
    filesystemPermissions: ["ops/reports"],
    browserPermissions: [],
    command: ["npm", "run", "maxx:opusclip", "--"],
  },
  {
    id: "maxx-software-factory",
    version: "0.1.0",
    purpose: "Route software work through the MAXX factory.",
    source: "pi-packages/maxx/skills/maxx-software-factory/SKILL.md",
    health: "ready",
    mutation: "mutating",
    approvalPolicy: "approval_required",
    requiredEnvironment: [],
    filesystemPermissions: ["repository"],
    browserPermissions: [],
  },
  {
    id: "maxx-skill-router",
    version: "0.1.0",
    purpose: "Choose the smallest trusted skill chain.",
    source: "pi-packages/maxx/skills/maxx-skill-router/SKILL.md",
    health: "ready",
    mutation: "read_only",
    approvalPolicy: "automatic",
    requiredEnvironment: [],
    filesystemPermissions: ["pi-packages/maxx/registry:read"],
    browserPermissions: [],
  },
  {
    id: "land-the-plane",
    version: "0.1.0",
    purpose: "Run the review, verification, and branch-close gate.",
    source: "pi-packages/maxx/skills/land-the-plane/SKILL.md",
    health: "ready",
    mutation: "mutating",
    approvalPolicy: "approval_required",
    requiredEnvironment: [],
    filesystemPermissions: ["repository"],
    browserPermissions: ["navigate", "extract", "screenshot"],
  },
];
